[package]
name = "drand-client-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
url = "2.3.1"
reqwest = { version = "0.11", features = ["blocking"] }
json = "0.12.4"
bls-signatures = "0.13.0"
thiserror = "1.0.38"