[package]
name = "drand-client-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = { version = "0.4.3", features = ["serde"] }
url = "2.3.1"
reqwest = { version = "0.11", features = ["blocking"] }
json = "0.12.4"
bls-signatures = "0.13.0"
thiserror = "1.0.38"
sha256 = "1.1.1"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"