name: build and test
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt -- --check
      - run: cargo clippy -- -Dwarnings
      - run: cargo test -- --nocapture
      - run: cargo build --release --all-features